baseURL = "/"
languageCode = "en-us"
title = "From Here To Insecurity"
theme = "minimal"
author = "Ash Virex"

[params]
  tagline = "...And Out Come The Exploits"
  
[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.148.1"
